Added priority to  todos
shreymahendru/floater pull request #4
Opened 2020-08-07 19:34 UTC by albertkur

View todo page and priority for todos

2020-08-13 17:01 UTC, shreymahendru requested changes

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/manage_todo/manage_todo_description/manage_todo_description_page_state.dart
> +    this._scopedNavigator.pushNamed(Routes.manageTodoPriority);
Since you removed the async call, remove the `async` keyword from the method signature of submit.

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/manage_todo/manage_todo_priority/manage_todo_priority_page.dart
> +            child: Column(
I don't think you need the `Center` in you are setting the `mainAxisAlignment` and `mainAxisAlignment` as center

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/routes.dart
> +  static const viewTodo = "/viewTodo?{todo?: object}";
Keep the flow routes together

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/todos/todos_page.dart
> +          color: Colors.red, borderRadius: BorderRadius.circular(30)),
Trailing  comma

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/todos/todos_page.dart
> +        alignment: Alignment.centerRight,
Always keep the widget properties before `child` or `children` of the widget.

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/todos/todos_page_state.dart
> +  void onSwipeDelete(Todo todo) {
`.removeTodo` is supposed to be an `async` call should have a loading and wrapped in try-catch

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/view_todo/view_todo_state.dart
> +    this.onInitState(() {});
don't need to use this here

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/view_todo/view_todo_state.dart
> +  ViewTodoState(Todo todo) : super() {
assign todo to a private class variable in the state and expose it through a getter to the page

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/view_todo/view_todo_state.dart
> +  Future<void> onEditTodoPressed(Todo todo) async {
Use the private variable mentioned above, no need to pass it to the function.

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/pages/view_todo/view_todo_state.dart
> +  final _navigator = NavigationService.instance.retrieveNavigator("/");
`final` variables on the top of the class always!!

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/sdk/todo/proxies/mock_todo_proxy.dart
> +  String get priority => this._dto.priority;
Make priority an `enum` don't use strings. And make appropriate changes, where ever it's used.

2020-08-13 17:01 UTC, shreymahendru commented on example/lib/sdk/todo/services/todos_service/todos_service.dart
> +  void removeTodo(Todo todo);
Should be a `Future<void>` not `void` as this is supposed to be an asynchronous network call which we are mocking with the current service implementation.

2020-08-14 16:40 UTC, albertkur commented on example/lib/pages/manage_todo/manage_todo_priority/manage_todo_priority_page.dart
> +            child: Column(
this one doesn't work without the `Center`. `crossAxisAlignment` seems useless here, so i removed that

2025-12-08 09:28 UTC, closed without merging